spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://52.78.41.121:3306/portfolio
    username: portfolio
    password: Whdgns1!

---
spring:
  profiles:  aaaa

iot: 
  home:
    path: a/a/a/a
    
---

spring:
  profiles:  bbbb
   
iot: 
  home:
    path: b/b/b/b