
restTemplate:
  factory:
    readTimeout: 5000 
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5 
    
iot:
  home:
    path: /data

logging:
  path: c:/dev/log/  

---
spring:
  profiles: dev
  
logging:
  path: /log/spring/
  file: log-file  