spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://52.78.41.121:3306/portfolio
    username: portfolio
    password: Whdgns1!
    
restTemplate:
  factory:
    readTimeout: 5000 
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5 
    
iot:
  home:
    path: /data
